---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "habla-config"
  namespace: "default"
  labels:
    app: "habla"
data:
  DB_NAME: "habla"
  SERVER_PORT: "80"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "habla"
  namespace: "default"
  labels:
    app: "habla"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "habla"
  template:
    metadata:
      labels:
        app: "habla"
    spec:
      containers:
      - name: "habla"
        image: "gcr.io/habla-215902/habla:v1.4.1"
        env:
        - name: "DB_NAME"
          valueFrom:
            configMapKeyRef:
              key: "DB_NAME"
              name: "habla-config"
        - name: "SERVER_PORT"
          valueFrom:
            configMapKeyRef:
              key: "SERVER_PORT"
              name: "habla-config"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        volumeMounts:
          - name: firebase-service-account
            mountPath: /secrets/firebase
            readOnly: true
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=habla-215902:southamerica-east1:habla=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: firebase-service-account
          secret:
            secretName: firebase-service-account
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "habla-hpa"
  namespace: "default"
  labels:
    app: "habla"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "habla"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  name: habla-api
  labels:
    app: habla
spec:
  selector:
    app: habla
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: "35.199.82.46"